version: "3"

services:
#   lavalink:
#     build:
#       context: ./lavalink_server
#       dockerfile: Dockerfile
#     container_name: music-lavalink
#     restart: unless-stopped
#     expose:
#       - 2333

  discord_bot:
    build: 
      context: ./bot
      dockerfile: Dockerfile 
    container_name: gang_bang_music
    restart: always
    # depends_on:
    #   - lavalink

networks:
  default:
    external:
      name: nginx-networks