version: "3"

services:
  lavalink:
    build:
      context: ./lavalink_server
      dockerfile: Dockerfile
    container_name: music-lavalink
    restart: unless-stopped
    # volumes:
    #   - ./lavalink_server/application.yml:/opt/Lavalink/application.yml:ro
    expose:
      - 2333

  discord_bot:
    build: 
      context: ./bot
      dockerfile: Dockerfile 
    container_name: gang_bang_music
    restart: always
    depends_on:
      - lavalink

networks:
  default:
    external:
      name: nginx-networks