plugins:
  youtube:
    enabled: true
    clients: ["TVHTML5EMBEDDED", "MUSIC", "WEB"]
  dunctebot:
      ttsLanguage: "ru-RU" # language of the TTS engine
      sources:
          # true = source enabled, false = source disabled
          getyarn: false # www.getyarn.io
          clypit: false # www.clyp.it
          tts: false # speak:Words to speak
          pornhub: true # should be self-explanatory
          reddit: true # should be self-explanatory
          ocremix: false # www.ocremix.org
          tiktok: true # tiktok.com
          mixcloud: false # mixcloud.com
          soundgasm: false # soundgasm.net
  lavasrc:
    providers: # Custom providers for track loading. This is the default
      - 'ytsearch:"%ISRC%"' # If ISRC available, search on youtube
      - "ytmsearch:%QUERY%" # If you want music.youtube results first
      - "ytsearch:%QUERY%" # If no result found on music.youtube, search on www.youtube
      - "scsearch:%QUERY%" # Last try to search on soundcloud.
      - 'spsearch:%QUERY%'
    sources:
      spotify: true # Enable Spotify source
      applemusic: false # Enable Apple Music source
      deezer: false # Enable Deezer source
      yandexmusic: true # Enable Yandex Music source
      flowerytts: false # Enable Flowery TTs source
      youtube: false # Enable YouTube search source (https://github.com/topi314/LavaSearch)
    spotify:
      clientId: "b458566df412473d800daacdd5937e8f"
      clientSecret: "1b5aedea6eb04358aaebee7d76047f80"
      countryCode: "US" # the country code you want to use for filtering the artists top tracks. See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
      playlistLoadLimit: 6 # The number of pages at 100 tracks each
      albumLoadLimit: 6 # The number of pages at 50 tracks each
    yandexmusic:
      accessToken: "-------------------" # the token used for accessing the yandex music api. See https://github.com/TopiSenpai/LavaSrc#yandex-music
server: # REST and WS server
  port: 2333
  address: 0.0.0.0
lavalink:
  plugins:
    # - dependency: "com.github.topi314.lavasearch:lavasearch-plugin:1.0.0"
    #   repository: "https://maven.topi.wtf/releases"
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.1.1"
      repository: "https://maven.topi.wtf/releases"
    - dependency: "com.dunctebot:skybot-lavalink-plugin:1.7.0"
      repository : "https://maven.lavalink.dev/releases" # (optional on laalink 4)
      snapshot: false # (optional, tells lavalink to use the default snaptshot repository instead)
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.4.0"
      snapshot: false # Set to true if you want to use a snapshot version.
  server:
    password: "maybeiwasboring"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    bufferDurationMs: 400 # The duration of the NAS buffer. Higher values fare better against longer GC pauses. Minimum of 40ms, lower values may introduce pauses.
    frameBufferDurationMs: 5000 # How many milliseconds of audio to keep buffered
    opusEncodingQuality: 10 # Opus encoder quality. Valid values range from 0 to 10, where 10 is the best quality but is the most expensive on the CPU.
    resamplingQuality: MEDIUM # Quality of resampling operations. Valid values are LOW, MEDIUM and HIGH, where HIGH uses the most CPU.
    trackStuckThresholdMs: 10000 # The threshold for how long a track can be stuck. A track is stuck if it does not return any audio data.
    useSeekGhosting: true # Seek ghosting is the effect where whilst a seek is in progress, the audio buffer is read from until empty, or until seek is ready.
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

  # ratelimit:
  #     ipBlocks: ["1234:1234:1234::/48"] # list of ip blocks/
  #     strategy: "LoadBalance" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
  #     searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing


metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO

  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000